# Generated by Django 3.2.3 on 2022-03-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qusetion',
            new_name='question',
        ),
    ]
